"""add heading and brief columns to embeddings

Revision ID: 02a36fdf1809
Revises: 538ef27f7bd4
Create Date: 2026-04-01 21:00:31.075004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a36fdf1809'
down_revision: Union[str, Sequence[str], None] = '538ef27f7bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('heading', sa.Text(), nullable=True))
    op.add_column('embeddings', sa.Column('brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'brief')
    op.drop_column('embeddings', 'heading')
    # ### end Alembic commands ###
